// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace LoaderScssNamespace {
  export interface ILoaderScss {
    load: string;
    loader: string;
  }
}

declare const LoaderScssModule: LoaderScssNamespace.ILoaderScss;

export = LoaderScssModule;
