// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace MasterScssNamespace {
    export interface IMasterScss {
        master: string;
    }
}

declare const MasterScssModule: MasterScssNamespace.IMasterScss;

export = MasterScssModule;
